
const CREATE = {
    REQUEST : "LOAN_CREATE_REQUEST",
    SUCCESS : "LOAN_CREATE_SUCCESS",
    ERROR:"LOAN_CREATE_ERROR",
    RESET : "LOAN_CREATE_RESET"
}

const DETAILS = {
    REQUEST : "LOAN_DETAILS_REQUEST",
    SUCCESS : "LOAN_DETAILS_SUCCES",
    ERROR : "LOAN_DETAILS_ERROR",
    RESET : "LOAN_DETAILS_RESET",
}

const LIST = {
    REQUEST : "LOAN_LIST_REQUEST",
    SUCCESS : "LOAN_LIST_SUCCES",
    ERROR : "LOAN_LIST_ERROR",
    RESET : "LOAN_LIST_RESET"
}

const COUNT = {
    REQUEST : "LOAN_COUNT_REQUEST",
    SUCCESS : "LOAN_COUNT_SUCCESS",
    ERROR : "LOAN_COUNT_ERROR",
    RESET : "LOAN_COUNT_RESET",
}

const ACTIVITY = {
    REQUEST : "LOAN_ACTIVITY_REQUEST",
    SUCCESS : "LOAN_ACTIVITY_SUCCESS",
    ERROR : "LOAN_ACTIVITY_ERROR",
    RESET : "LOAN_ACTIVITY_RESET",
}

const PAY_INTEREST = {
    REQUEST : "PAY_INTEREST_REQUEST",
    SUCCESS : "PAY_INTEREST_SUCCESS",
    ERROR : "PAY_INTEREST_ERROR",
    RESET : "PAY_INTEREST_RESET",
}

const CLOSE_ACCOUNT = {
    REQUEST : "CLOSE_ACCOUNT_REQUEST",
    SUCCESS : "CLOSE_ACCOUNT_SUCCESS",
    ERROR : "CLOSE_ACCOUNT_ERROR",
    RESET : "CLOSE_ACCOUNT_RESET",
}

export const LoanActionTypes = {
    ADD : CREATE,
    DETAILS : DETAILS,
    COUNT : COUNT,
    LIST : LIST,
    ACTIVITY : ACTIVITY,
    INTEREST : PAY_INTEREST,
    CLOSE : CLOSE_ACCOUNT
}